on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

name: Test

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15.x

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Go Test Suite
        run: go test ./... -race -coverprofile=coverage.txt -covermode=atomic

      - name: Upload to CodeCov
        uses: codecov/codecov-action@v1
        with:
          file: ./coverage.txt
